version: "3.8"
services:
  backend:
    build:
      context: ./f4u-backend
    container_name: f4u-backend
    ports:
      - "8080:8080"
    networks:
      - f4u-net
    environment:
      - SPRING_PROFILES_ACTIVE=dev

  frontend:
    build:
      context: ./f4u-frontend
      args:
        REACT_APP_API_URL: http://backend:8080
    container_name: f4u-frontend
    ports:
      - "3000:80"
    networks:
      - f4u-net

networks:
  f4u-net:
    driver: bridge
